server:
  port: 8001
spring:
  rabbitmq:
    addresses: localhost
    port: 5672
    username: guest
    password: guest
    # 手动确认发送消息
    publisher-confirm-type: correlated
    # 打开消息返回
    publisher-returns: true