server:
  port: 8010
spring:
  rabbitmq:
    addresses: localhost
    port: 5672
    username: guest
    password: guest
    # 确认消息是否成功发送
    publisher-confirm-type: correlated
    # 消息在未被队列接收时返回
    publisher-returns: true
    template:
      mandatory: true